dictionary:
  initial-load: false
  base-url: https://url.to.the.online.dictionaty/
  letters:
    url: https://url.to.the.online.dictionaty/index.php
    selector: ".letter a"
  groups:
    cron: "0 * * * * *"
    selector: ".row .cont_link"
  words:
    cron: "0 * * * * *"
    selectors:
      description: "div.toggle-sum div.toggle-content"
      orpho: "div.toggle-content section.orfo"
      word: ".row .cont_link"

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000
  port: 8080

db:
  host: localhost
  user: dic
  password: dic
  database: dictionary
  port: 5432
  url: jdbc:postgresql://${db.host}:${db.port}/${db.database}


spring:
  application.name: dictionary-crawler
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibrenate.globally_quoted_identifiers: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  jackson.serialization.write_dates_as_timestamps: false
